apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/realtime-satellite-api/api
    newName: ghcr.io/startupnationlabs/realtime-satellite-api/api
    newTag: e2d7c261e09520e215bc05725c8ba77edbcc67a8
    
patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml
