apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/realtime-satellite-api/api
    newName: ghcr.io/startupnationlabs/realtime-satellite-api/api
    newTag: 1c542335d98ecf15b6379401f817986f2f90d4c7


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml
